"""Add ConversationAnalytics

Revision ID: a6a13ee2d3d0
Revises: d3f3f2dcead4
Create Date: 2026-09-14 19:19:11.963851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6a13ee2d3d0'
down_revision: Union[str, None] = 'd3f3f2dcead4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_analytics',
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('total_tokens_used', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Float(), nullable=True),
    sa.Column('completion_tokens', sa.Float(), nullable=True),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_analytics_business_id'), 'conversation_analytics', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversation_analytics_conversation_id'), 'conversation_analytics', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_analytics_id'), 'conversation_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_conversation_analytics_id'), table_name='conversation_analytics')
    op.drop_index(op.f('ix_conversation_analytics_conversation_id'), table_name='conversation_analytics')
    op.drop_index(op.f('ix_conversation_analytics_business_id'), table_name='conversation_analytics')
    op.drop_table('conversation_analytics')
    # ### end Alembic commands ###
